# Generated by Django 2.1.7 on 2019-04-11 14:28

import easy_thumbnails.fields
from django.db import migrations

import utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carservicecategory",
            name="image",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=utils.mixins.image_path,
                verbose_name="Image",
            ),
        ),
    ]
