# Generated by Django 2.1.7 on 2019-04-22 15:01
#
# NOTE: colorful (django-colorful) dependency was removed during the Django 5.2
# upgrade. Original field was colorful.fields.RGBColorField(max_length=7).
# Replaced with a plain CharField(max_length=7) here so migration history
# still replays on a fresh DB without the removed package.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0002_carservicecategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="carcolor",
            name="hex_color",
            field=models.CharField(
                max_length=7, blank=True, default=None, null=True
            ),
        ),
    ]
