# Generated by Django 2.1.7 on 2019-04-22 15:01

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0002_carservicecategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="carcolor",
            name="hex_color",
            field=colorful.fields.RGBColorField(
                blank=True, default=None, null=True
            ),
        ),
    ]
