"""
Django settings for road_helper project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os, sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Common path section
PUBLIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, '..', 'media'))
PROJECT_ROOT = os.path.abspath(os.path.join(BASE_DIR, '..'))
DATADIR_ROOT = os.path.abspath(os.path.join(BASE_DIR, '..', 'datadir'))

# # insert apps and libs dirs to sys.path
for path in ('apps', 'libs'):
    path = os.path.abspath(os.path.join(PROJECT_ROOT, '%s' % path))
    path in sys.path or sys.path.insert(0, path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^t87c7f_vti$%_&dwb69kc22$bvh$-$rog9_b(9*r6^6o!^tp1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

CONTRIB_APPS = [
    'bootstrap_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis'
]

PROJECT_APPS = [
    'authorization.apps.AuthorizationConfig',
    'account.apps.AccountConfig',
    'utils.apps.UtilsConfig',
    'versioning.apps.VersioningConfig',
    'userprofile.apps.UserprofileConfig',
    'catalog.apps.CatalogConfig',
    'base.apps.BaseConfig',
    'order.apps.OrderConfig'
]

EXTERNAL_APPS = [
    'rest_framework',
    'rest_framework_gis',
    'rest_framework.authtoken',
    'rest_framework_swagger',
    'solo',
    'django_filters',
    'phonenumber_field',
    'easy_thumbnails',
    'fcm_django',
    'easy_select2',
    'inline_actions',
    'django_object_actions',
    'multiselectfield',

]

INSTALLED_APPS = CONTRIB_APPS + PROJECT_APPS + EXTERNAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USERNAME'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOSTNAME'),
        'PORT': os.environ.get('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 9,
        }

    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'account.User'
LOGIN_URL = 'admin:login'
LOGOUT_URL = 'admin:logout'


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (
    os.path.abspath(os.path.join(BASE_DIR, 'locale')),
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'media')
MEDIA_URL = '/media/'

# STATICFILES_DIRS = (
#     os.path.join(PROJECT_ROOT, 'static'),
# )


# Celery settings
CELERY_BROKER_URL = 'redis://localhost:6379/1'
USE_CELERY = True

# Versioning
AVAILABLE_VERSIONS = {
    'future': '1.0.1',
    'current': '1.0.0',
}


# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 15,
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_VERSION': (AVAILABLE_VERSIONS['current'],),
    'ALLOWED_VERSIONS': AVAILABLE_VERSIONS.values(),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

REST_DATE_FORMAT = '%m-%d-%Y'
REST_DATETIME_FORMAT = '%m-%d-%Y %H:%M:%S'


# Thumbnail settings
THUMBNAIL_ALIASES = {
    '': {
        'tiny': {'size': (100, 0), },
        'small': {'size': (480, 0), },
        'middle': {'size': (700, 0), },
        'large': {'size': (1500, 0), },
        'default': {'size': (300, 200), 'crop': True},
        'gallery': {'size': (240, 160), 'crop': True},
        'news_large': {'size': (1500, 1000), 'crop': True},
        'news_tiny': {'size': (300, 200), 'crop': True}
    },
}


# CORS Config
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = False


# SMS
SMS_SEND_DELAY = 30
SMS_EXPIRATION = 5  # minutes
SMS_CODE_LENGTH = 4
SMS_INPUT_ATTEMPTS = 2
SMS_BLOCKING_PERIOD = 86400  # 24 hours in seconds
SEND_SMS = True  # Actual sms sending switcher


# Django Rest Swagger
SWAGGER_SETTINGS = {
    'JSON_EDITOR': False,
    'SHOW_REQUEST_HEADERS': True,
    'SECURITY_DEFINITIONS': {
        'api_key': {
            'type': 'apiKey',
            'description': 'Token authorization',
            'name': 'Authorization',
            'in': 'header',
        }
    },
}
