stages:
  - build
  - release
  - deploy
  - tests

variables:
  KANIKO_VERSION: "debug-v1.3.0"
  PROJECT_DOCKER_REGISTRY: "registry.gitlab.com/agencypro"
  DOCKER_IMAGE_NAME: "registry.gitlab.com/agencypro/roadhelpbackend"

before_script:
  - export VERSION="$(date '+%Y.%m.%d.%H.%M')"

build_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:${KANIKO_VERSION}
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination ${DOCKER_IMAGE_NAME}:${VERSION}
      --cache-ttl=1h
      --cache=true
      --cache-repo=${DOCKER_IMAGE_NAME}/cache
  only:
    refs:
      - master
  tags:
    - docker

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "running release"
    - echo "$VERSION"
    - release-cli create --name "Release $VERSION" --description "Автоматическая сборка" --tag-name "$VERSION"
  only:
    - master
  tags:
    - docker

run-django-test:
  image: registry.gitlab.com/agencypro/roadhelpbackend:python-3.7.2-based
  stage: tests
  services:
    - name: postgis/postgis:10-3.0
      alias: postgres
  variables:
    POSTGRES_DB: "roadhelper"
    POSTGRES_USER: "roadhelper"
    POSTGRES_PASSWORD: "roadhelper"
    DB_HOST: "postgres"
  script:
    - make dj-test
  allow_failure: true
  tags:
    - docker

black:
  image: registry.gitlab.com/agencypro/roadhelpbackend:python-3.7.2-based
  stage: tests
  script:
    - make black
  allow_failure: true
  tags:
    - docker

mypy:
  image: registry.gitlab.com/agencypro/roadhelpbackend:python-3.7.2-based
  stage: tests
  script:
    - make mypy
  allow_failure: true
  tags:
    - docker

isort:
  image: registry.gitlab.com/agencypro/roadhelpbackend:python-3.7.2-based
  stage: tests
  script:
    - make isort
  allow_failure: true
  tags:
    - docker

flake8:
  image: registry.gitlab.com/agencypro/roadhelpbackend:python-3.7.2-based
  stage: tests
  script:
    - make flake8
  allow_failure: true
  tags:
    - docker
