version: '3'
services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    command:
      [
          "/bin/bash",
          "-c",
          "make start && make run-gunicorn",
      ]

  celery:
    build:
      context: .
    command:
      [
          "/bin/bash",
          "-c",
          "make celery",
      ]
