# Generated by Django 2.1.7 on 2019-05-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_pushnotificationconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushNotificationSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField(verbose_name="time")),
            ],
            options={
                "verbose_name": "Push-notification schedule",
                "verbose_name_plural": "Push-notification schedules",
            },
        ),
        migrations.AlterField(
            model_name="pushnotificationconfiguration",
            name="geo_position_lifetime",
            field=models.TimeField(
                blank=True,
                help_text="Profile geo-position lifetime",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pushnotificationconfiguration",
            name="radius",
            field=models.FloatField(
                blank=True,
                default=5000,
                help_text="Radius in meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pushnotificationconfiguration",
            name="notification_schedule",
            field=models.ManyToManyField(to="base.PushNotificationSchedule"),
        ),
    ]
