# Generated by Django 2.1.7 on 2019-05-21 14:39

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_auto_20190520_1417"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushnotificationconfiguration",
            name="geo_position_lifetime",
            field=models.TimeField(
                blank=True,
                default=datetime.time(6, 0),
                help_text="Profile geo-position lifetime",
                null=True,
                verbose_name="Geo position lifetime",
            ),
        ),
        migrations.AlterField(
            model_name="pushnotificationconfiguration",
            name="notification_schedule",
            field=models.ManyToManyField(
                to="base.PushNotificationSchedule",
                verbose_name="Notification schedule",
            ),
        ),
        migrations.AlterField(
            model_name="pushnotificationconfiguration",
            name="radius",
            field=models.FloatField(
                blank=True,
                default=5000,
                help_text="Radius in meters",
                null=True,
                verbose_name="Radius",
            ),
        ),
    ]
