# Generated by Django 2.1.7 on 2019-10-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_auto_20190711_1310"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="push",
            field=models.BooleanField(default=False, verbose_name="Push"),
        ),
    ]
