# Generated by Django 2.1.7 on 2019-12-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_userverificationconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="recommendation",
            field=models.BooleanField(
                default=False, verbose_name="Recommendation"
            ),
        ),
    ]
