# Generated by Django 2.1.7 on 2020-01-30 14:20
#
# NOTE: image_cropping dependency was removed during the Django 5.2 upgrade.
# This migration now creates a plain CharField in place of the old
# ImageRatioField so existing DB state stays compatible. The field is
# dropped altogether by a later migration (0026_*).
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_newsletter_refused"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="cropping",
            field=models.CharField(max_length=255, blank=True, default="", verbose_name="cropping"),
        ),
    ]
