# Generated by Django 2.1.7 on 2020-01-30 14:20

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_newsletter_refused"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "600x600",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=True,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="cropping",
            ),
        ),
    ]
