# Generated by Django 2.2 on 2020-02-05 12:39

import django.db.models.deletion
import django.utils.timezone
import image_cropping.fields
from django.conf import settings
from django.db import migrations, models

import utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0019_newsletter_cropping"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Date created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date updated"
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        default="",
                        max_length=1024,
                        verbose_name="Text comment",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter comment",
                "verbose_name_plural": "Newsletter comments",
            },
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "600x600",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=True,
                help_text=None,
                hide_image_field=False,
                size_warning=True,
                verbose_name="cropping",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="image",
            field=image_cropping.fields.ImageCropField(
                blank=True,
                default=None,
                null=True,
                upload_to=utils.mixins.image_path,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="text",
            field=models.TextField(
                blank=True, default="", verbose_name="Text"
            ),
        ),
        migrations.CreateModel(
            name="NewsletterLike",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Date created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date updated"
                    ),
                ),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.Newsletter",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter like",
                "verbose_name_plural": "Newsletter likes",
            },
        ),
        migrations.CreateModel(
            name="NewsletterCommentLike",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Date created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date updated"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.NewsletterComment",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment like",
                "verbose_name_plural": "Comment likes",
            },
        ),
        migrations.AddField(
            model_name="newslettercomment",
            name="newsletter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="base.Newsletter",
            ),
        ),
    ]
