# Generated by Django 2.2 on 2020-02-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_auto_20200222_2030"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="as_admin",
            field=models.BooleanField(
                default=False, verbose_name="Publish as administrator"
            ),
        ),
    ]
