# Generated by Django 2.2 on 2021-10-20 08:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0023_newsletter_as_admin"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="newsletterlike",
            unique_together={("newsletter", "owner")},
        ),
    ]
