# Generated by Django 2.2 on 2021-10-20 08:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0024_auto_20211020_0831"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="newslettercommentlike",
            unique_together={("comment", "owner")},
        ),
    ]
