---

- name: server-upgrade
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  when: action == "upgrade"

- name: Install minioclient
  get_url:
    url: "{{ minio_client.url }}"
    dest: "{{ minio_client.path }}/{{ minio_client.name }}"
    mode: 0755
  when: action == "install"

- name: install soft
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "ansible"
    - "vim"
    - "postgresql-common"
    - "postgresql-server-dev-all"
    - "pgxnclient"
    - "nginx"
    - "git"
    - "gnupg2"
    - "pass"
    - "docker"
  when: action == "install"

- name: gnupg2 pass
  shell: gpg2 --full-generate-key
  when: action == "gnupg2"

- name: templating docker-compose
  template:
    src: docker-compose.prod.yml.j2
    dest: ~/docker-compose.prod.yml
  when: action == "release"