# Generated by Django 2.1.7 on 2019-04-08 09:19

import easy_thumbnails.fields
from django.db import migrations

import utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0005_auto_20190404_0626"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilegallery",
            name="is_main",
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=utils.mixins.image_path,
                verbose_name="Image",
            ),
        ),
    ]
