# Generated by Django 2.1.7 on 2019-10-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0011_auto_20190708_1223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilecar",
            name="license_plate",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="License plate",
            ),
        ),
    ]
