# Generated by Django 2.2 on 2021-10-15 08:12

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0014_auto_20191223_1155"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="profilelocation",
            managers=[
                ("gis", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="profilelocation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                default=django.contrib.gis.geos.point.Point(0, 0),
                null=True,
                srid=4326,
                verbose_name="Location",
            ),
        ),
    ]
