# Generated by Django 2.2 on 2021-10-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0015_auto_20211015_0812"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilelocation",
            name="lat",
            field=models.DecimalField(
                decimal_places=6, default=0.0, max_digits=9
            ),
        ),
        migrations.AddField(
            model_name="profilelocation",
            name="lng",
            field=models.DecimalField(
                decimal_places=6, default=0.0, max_digits=9
            ),
        ),
    ]
