# Generated by Django 2.2 on 2021-10-20 08:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userprofile", "0016_auto_20211020_0806"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="profilelocation",
            index_together={("user", "lng", "lat")},
        ),
    ]
