# Generated by Django 2.1.7 on 2019-04-11 15:10

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_assistancerequest_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistancerequest",
            name="contact_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                verbose_name="User contact phone",
            ),
        ),
        migrations.AddField(
            model_name="assistancerequest",
            name="text_address",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Text address",
            ),
        ),
    ]
