# Generated by Django 2.2 on 2021-10-20 08:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0008_auto_20211020_0808"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="assistancerequest",
            index_together={("user", "lng", "lat", "status")},
        ),
    ]
