# Generated by Django 2.1.7 on 2019-03-05 12:13

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('publish', models.BooleanField(default=False, verbose_name='Publish')),
                ('publish_date', models.DateTimeField(help_text='Uses instead created if set', verbose_name='Publish date')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'Newsletter',
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('event', models.PositiveSmallIntegerField(choices=[(0, 'Initialization'), (1, 'Create assistance request'), (2, 'New message')], default=0, verbose_name='Event')),
                ('status', models.BooleanField(blank=True, default=False, null=True, verbose_name='Status')),
                ('sent_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='Sent notifications count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Push notification',
                'verbose_name_plural': 'Push notifications',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'A service with that phone already exists.'}, max_length=128, verbose_name='Service contact phone')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ServiceCategory')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
