# Generated by Django 2.1.7 on 2019-04-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="short_description",
            field=models.CharField(
                default=None,
                max_length=255,
                null=True,
                verbose_name="Short description",
            ),
        ),
    ]
