# Generated by Django 2.1.7 on 2019-04-09 11:06

from django.db import migrations
import easy_thumbnails.fields
import utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_newsletter_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, null=True, upload_to=utils.mixins.image_path, verbose_name='Image'),
        ),
    ]
