# Generated by Django 2.1.7 on 2019-05-16 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_newsletter_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.FloatField(default=5000)),
                ('geo_position_lifetime', models.TimeField(default=datetime.timedelta(seconds=1800), help_text='Lifetime for user geo-position', verbose_name='User geo-position lifetime')),
            ],
            options={
                'verbose_name': 'Push notification configuration',
            },
        ),
    ]
