# Generated by Django 2.1.7 on 2019-05-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190517_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushnotificationschedule',
            options={'ordering': ('time',), 'verbose_name': 'Push-notification schedule', 'verbose_name_plural': 'Push-notification schedules'},
        ),
    ]
