# Generated by Django 2.2 on 2020-02-07 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_auto_20200205_1239"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslettercomment",
            name="newsletter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="base.Newsletter",
            ),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="event",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Initialization"),
                    (1, "Create assistance request"),
                    (2, "New message"),
                    (3, "Friend request"),
                    (4, "Newsletter"),
                    (5, "Newsletter like"),
                    (6, "New newsletter comment"),
                ],
                default=0,
                verbose_name="Event",
            ),
        ),
    ]
