# Generated by Django 2.1.7 on 2019-12-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0002_auto_20190326_1502"),
    ]

    operations = [
        migrations.AddField(
            model_name="smscode",
            name="mode",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "SMS"), (1, "CALL")], default=0
            ),
        ),
    ]
