import environ

env = environ.Env(
    DEBUG=(bool, True),
    REDIS_URL=(str, "REDIS_URL"),
    REDIS_LOCATION=(str, "REDIS_LOCATION"),
    REDIS_PASSWORD=(str, "REDIS_PASSWORD"),
    REDIS_PORT=(str, "REDIS_PORT"),

    DB_HOST=(str, "127.0.0.1"),
    DB_NAME=(str, "roadhelper"),
    DB_PORT=(int, 5432),
    DB_USER=(str, "roadhelper"),
    DB_PASSWORD=(str, "roadhelper"),
    REDIS_DB=(str, "REDIS_DB"),
    CELERY_BROKER_URL=(str, "CELERY_BROKER_URL"),
    TIME_ZONE=(str, "Europe/Moscow"),
    USE_TZ=(bool, True),
    USE_I18N=(bool, True),
    USE_L10N=(bool, True),
    USE_CELERY=(bool, False),
    SECRET_KEY=(str, "^t87c7f_vti$%_&dwb69kc22$bvh$-$rog9_b(9*r6^6o!^tp1"),
    SENTRY_DSN=(
        str,
        "https://6dca49f5f11743338eecb732e335053c@sentry.io/1467323",
    ),
    SMS_SERVICE=(str, "http://smsc.ru/sys/send.php"),
    SMS_LOGIN=(str, "ilyaarzumanyan92"),
    SMS_PASSWORD=(str, "93Damybee281"),
    SMS_SENDER=(str, "RoadHelper"),
    APPROVE_ACCOUNT=(str, "+79000000000"),
    TEST_SMS_CODE=(bool, False),
    USE_SMS=(bool, False),
    PAGE_SIZE=(int, 15),
    SMS_SEND_DELAY=(int, 60),
    SMS_CODE_LENGTH=(int, 5),
    SMS_INPUT_ATTEMPTS=(int, 2),
    SMS_BLOCKING_PERIOD=(int, 86400),
    NEWSLETTER_USERPROFILE_ID=(int, 1),
    NOTIFY_USERS_ON_ENTER_OR_LEAVE_ROOMS=(bool, True),
    REQUEST_RELEVANCE=(int, 30),
    DEFAULT_REQUEST_RADIUS=(int, 100000),
    FCM_SERVER_KEY=(
        str,
        "AAAAjcLTzLw:APA91bGE_GYkVBsKZs5S1NH3ZLmeaT7RA0-MT1a6NzeGNjUoP3rfULN2gP1zd2gsnpFVVbQjlm5EV9godH5RNarcAhxahpb9i4p2rKNa40TTT5JtrxraR0y3FZ6JlfE2Z1KTY-lWw9cM",  # noqa
    ),
    OTP_SERVICE=(str, "https://api.new-tel.net"),
    OTP_SERVER_KEY=(
        str,
        "f30a901fc45f7f082628a719f64d54ca486b7b3d0cf57714",
    ),
    OTP_SIGNATURE_KEY=(
        str,
        "ed839ad2c73e071886e0752a563f8e2dfafc7c1ce7f717d2",
    ),
    LIMIT_UNREAD_MESSAGES=(int, 3),
    MESSAGES_UPDATE_PERIOD=(int, 15),
    SESSION_SAVE_EVERY_REQUEST=(bool, True),
    DATA_UPLOAD_MAX_MEMORY_SIZE=(int, 104857600),
    FILE_UPLOAD_PERMISSIONS=(int, 0o644),
)
