# Generated by Django 2.1.7 on 2019-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Assistance request is available'), (0, 'Assistance request was expired'), (2, 'Assistance request was canceled')], default=1, verbose_name='Status'),
        ),
    ]
