# Generated by Django 2.1.7 on 2020-01-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_assistancerequestuserread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequestuserread',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_request_user_read', to='order.AssistanceRequest', verbose_name='Order'),
        ),
    ]
