# Generated by Django 2.1.7 on 2019-05-23 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_auto_20190423_0829"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "ordering": ("-created",),
                "verbose_name": "Chat message",
                "verbose_name_plural": "Chat messages",
            },
        ),
        migrations.AlterModelOptions(
            name="chatrole",
            options={
                "verbose_name": "Chat role",
                "verbose_name_plural": "Chat roles",
            },
        ),
        migrations.AlterModelOptions(
            name="chatroom",
            options={
                "verbose_name": "Chat room",
                "verbose_name_plural": "Chat rooms",
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="timestamp",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Recording date",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.TextField(verbose_name="Text message"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.ChatRoom",
                verbose_name="Room",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender",
            ),
        ),
        migrations.AlterField(
            model_name="chatrole",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_role",
                to="chat.ChatRoom",
                verbose_name="Room",
            ),
        ),
        migrations.AlterField(
            model_name="chatrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_role",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="is public"),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=24,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="participants",
            field=models.ManyToManyField(
                related_name="participants",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participants",
            ),
        ),
    ]
