---
version:
  docker_ce: 20.10.7

DOCKER_IMAGE_NAME: "registry.gitlab.com/agencypro/roadhelpbackend"
VERSION: "2021.10.20.13.41"

minio_client:
  url: "https://dl.min.io/client/mc/release/linux-amd64/mc"
  path: /usr/local/bin
  name: minioclient

pg_repack:
  url: "https://api.pgxn.org/dist/pg_repack/1.4.2/pg_repack-1.4.2.zip"
  dest: /home/root/

docker:
  registry: "registry.gitlab.com"
  user: "deploy"
  token: "aofLPv_Rc_z2pm9e5N7z"

roadhelpbackend_settings:
  - DEBUG: ""
  - REDIS_URL: ""
  - REDIS_PORT: ""
  - REDIS_DB: ""
  - DB_NAME: ""
  - DB_USERNAME: ""
  - DB_HOST: ""
  - DB_PORT: ""
  - DB_PASSWORD: ""
  - CELERY_BROKER_URL: ""
  - TIME_ZONE: ""
  - USE_TZ: ""
  - USE_I18N: ""
  - USE_L10N: ""
  - USE_CELERY: ""
  - SECRET_KEY: ""
  - SENTRY_DSN: ""
  - SMS_SERVICE: ""
  - SMS_PASSWORD: ""
  - SMS_SENDER: ""
  - APPROVE_ACCOUNT: ""
  - TEST_SMS_CODE: ""
  - USE_SMS: ""
  - PAGE_SIZE: ""
  - SMS_SEND_DELAY: ""
  - SMS_CODE_LENGTH: ""
  - SMS_INPUT_ATTEMPTS: ""
  - SMS_BLOCKING_PERIOD: ""
  - NEWSLETTER_USERPROFILE_ID: ""
  - NOTIFY_USERS_ON_ENTER_OR_LEAVE_ROOMS: ""
  - REQUEST_RELEVANCE: ""
  - DEFAULT_REQUEST_RADIUS: ""
  - FCM_SERVER_KEY: ""
  - OTP_SERVICE: ""
  - OTP_SERVER_KEY: ""
  - OTP_SIGNATURE_KEY: ""
  - LIMIT_UNREAD_MESSAGES: ""
  - MESSAGES_UPDATE_PERIOD: ""
  - SESSION_SAVE_EVERY_REQUEST: ""
  - DATA_UPLOAD_MAX_MEMORY_SIZE: ""
  - FILE_UPLOAD_PERMISSIONS: ""