# Generated by Django 2.1.7 on 2019-03-03 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Phone')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Waiting'), (1, 'Sent'), (2, 'Activated'), (3, 'Declined'), (4, 'Expired')], default=0)),
                ('code', models.CharField(max_length=4, verbose_name='Code')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'SMS code',
                'verbose_name_plural': 'SMS codes',
            },
        ),
    ]
