# Generated by Django 2.1.7 on 2019-03-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='code',
            field=models.CharField(max_length=5, verbose_name='Code'),
        ),
    ]
