# Generated by Django 2.1.7 on 2019-04-04 06:26

from django.db import migrations
import easy_thumbnails.fields
import utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_profilegallery_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilegallery',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, null=True, upload_to=utils.mixins.image_path, verbose_name='Image'),
        ),
    ]
