# Generated by Django 2.1.7 on 2019-04-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20190408_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='middle_name',
        ),
    ]
