# Generated by Django 2.1.7 on 2019-07-08 11:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userprofile", "0009_fcmdevice"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendlist",
            unique_together={("owner", "friend")},
        ),
    ]
