# Generated by Django 2.1.7 on 2019-07-08 12:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userprofile", "0010_auto_20190708_1111"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="blacklist",
            unique_together={("owner", "foe")},
        ),
        migrations.AlterUniqueTogether(
            name="friendrequest",
            unique_together={("owner", "invited")},
        ),
    ]
