# Generated by Django 2.1.7 on 2019-04-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatroom_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ("-created",)},
        ),
    ]
