# Generated by Django 2.1.7 on 2019-07-10 10:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_auto_20190523_1406'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatreadmessage',
            unique_together={('user', 'message')},
        ),
    ]
